### ISSUE TITLE
Which Scheme implementation does the Makefile rely on?

### ISSUE THREAD

**Issue by daveduthie** [namin/inc#5]
Hi, I'm keen to run the tests. 

Could you make a note in the README about which version of Scheme was used?

**Comment by daveduthie** [comment]
Ah, it's in the Dockerfile 😊 -> Chez Scheme.

**Comment by namin** [comment]
Feel free to send a pull request to clarify README.

**Comment by jaseemabid** [comment]
@daveduthie I wrote that Makefile, I should have been more precise. 🤦‍♂️

**Comment by namin** [comment]
Fix it. :)
